import Article from '@/components/article/Article'
import Head from 'next/head'
import React from 'react'
import game from '../../public/image/game.jpg'
import categoria from '../../public/image/categoriaventas.jpg'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/layout/Layout'

const article = () => {
    return (
        <>
            <Head>
                <title>Articulos</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                <Layout>
                <div className={styles.article_flex}>
                    <h1>Imaginación Triunfos ¡Conocimiento!</h1>
                    <div className={styles.article_container}>
                        <Article
                        title="prueba titulo"
                        img={categoria}
                        summary="este en un ensayo de un parrafo"
                        link="https://public.tableau.com/app/profile/heynar.soto.holguin/viz/VentasporCategoria_16818704851260/Dashboard3"
                        github="/"
                        type="proyectos feactud"
                        />
                    
                        <Article
                        title="prueba titulo"
                        img={game}
                        summary="este en un ensayo de un parrafo"
                        link="https://public.tableau.com/app/profile/heynar.soto.holguin/viz/gameofthorne/vistazogeneral"
                        github="/"
                        type="proyectos feactud"
                        />
                    
                        <Article
                        title="prueba titulo"
                        img={categoria}
                        summary="este en un ensayo de un parrafo"
                        link="https://public.tableau.com/app/profile/heynar.soto.holguin/viz/VentasporCategoria_16818704851260/Dashboard3"
                        github="/"
                        type="proyectos feactud"
                        />
                        <Article
                        title="prueba titulo"
                        img={game}
                        summary="este en un ensayo de un parrafo"
                        link="https://public.tableau.com/app/profile/heynar.soto.holguin/viz/gameofthorne/vistazogeneral"
                        github="/"
                        type="proyectos feactud"
                        />
                    </div>
                </div>
                </Layout>
            </main>
        </>
    )
}

export default article