import Projects from '@/components/projects/Projects'
import Head from 'next/head'
import React from 'react'
import styles from '@/styles/Home.module.css'
import web from '../../public/image/web.jpg'
import web2 from '../../public/image/web2.jpg'
import web3 from '../../public/image/web3.jpg'
import buga from '../../public/image/bugaprojects.jpg'
import Layout from '@/components/layout/Layout'

const projects = () => {
    return (
        <>
        <Head>
            <title>Proyectos</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <main>
            <Layout>
            <div className={styles.project_flex}>
                <h1>Imaginación Triunfos ¡Conocimiento!</h1>
            <div>
                <div className={styles.project_container}>
                    <Projects
                    title="prueba titulo"
                    img={buga}
                    summary="este en un ensayo de un parrafo"
                    link="https://mi-pueblo.vercel.app"
                    github="/"
                    type="proyectos feactud"
                    />
                
                    <Projects
                    title="prueba titulo"
                    img={web}
                    summary="este en un ensayo de un parrafo"
                    link="https://portafolio2hey.netlify.app"
                    github="/"
                    type="proyectos feactud"
                    />
                
                    <Projects
                    title="prueba titulo"
                    img={web2}
                    summary="este en un ensayo de un parrafo"
                    link="https://portafolioheynar.netlify.app"
                    github="/"
                    type="proyectos feactud"
                    />
                    <Projects
                    title="prueba titulo"
                    img={web3}
                    summary="este en un ensayo de un parrafo"
                    link="https://turismobuga.netlify.app/"
                    github="/"
                    type="proyectos feactud"
                    />
                </div>
            </div>
            </div>
            </Layout>
        </main>
    </>
    )
}

export default projects